[project]
name = "gppop"  # Required
version = "0.1.0"  # Required
description = "Non-parametric inference of the population of compact binaries from gravitational wave observations using binned Gaussian processes. Methods papers: https://arxiv.org/pdf/2511.22093, https://arxiv.org/abs/2304.08046, https://arxiv.org/abs/2404.03166, and, https://arxiv.org/abs/2511.22093, https://arxiv.org/abs/2607.28622."  # Optional
readme = "README.md" # Optional
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
  {name = "Anarya Ray", email = "anarya.ray@ligo.org" },
  {name = "Omkar Sridhar", email = "omkarnm1401@gmail.com" },
  {name = "Siddharth Mohite", email = "srmohite@uwm.edu" },
  {name = "Claude (Anthropic)"},
]
maintainers = [
  {name = "Anarya Ray", email = "anarya.ray@northwestern.edu" },
]

dependencies = [
    "numpy>=1.24",
    "torch>=2.7",
    "gpytorch>=1.11",
    "linear-operator>=0.5",
    "pyro-ppl>=1.9",
    "arviz>=0.17",
    "h5py>=3.8",
    "tqdm>=4.65",
    "astropy>=5.0",
    "seaborn>=0.13.2"
]

[project.optional-dependencies]
sklearn = ["scikit-learn>=1.3"]
plotting = ["matplotlib>=3.7", "seaborn>=0.13"]

[project.scripts]
run_gppop = "gppop.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
